# Generated by Django 5.2 on 2025-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_time_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
