# Generated by Django 5.2 on 2025-05-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_approached',
            new_name='is_approved',
        ),
    ]
