# Generated by Django 5.2 on 2025-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_is_approached_comment_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
