# Generated by Django 5.2 on 2025-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_login_require',
            field=models.BooleanField(default=False),
        ),
    ]
