# Generated by Django 5.2 on 2025-05-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_is_login_require'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_login_require',
            new_name='is_login_required',
        ),
    ]
